# Generated by Django 4.0.5 on 2022-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kingcounty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='data',
            name='crime_count_normalized',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='street_block',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
