# Generated by Django 4.0.5 on 2022-07-13 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingcounty', '0003_alter_data_crime_count_normalized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='street_block',
            new_name='county',
        ),
    ]
